### ISSUE TITLE
Support enabling full-text search in Interactive

### ISSUE THREAD

**Issue by robertwtucker** [robertwtucker/spt-charts#2]
Interactive R15+ provides full-text search through integration with Elasticsearch v7.10+.

Example from AKS/EKS charts:
```
interactive:
  fulltext:
    enabled: true
    host: "https://inspire-fulltext.$(NAMESPACE).svc.cluster.local:9200"
    username: esadmin
    password: pass
```
