### ISSUE TITLE
Ingress annotations need to match settings for the SPT Demo cluster

### ISSUE THREAD

**Issue by robertwtucker** [robertwtucker/spt-charts#32]
Currently, the Ingress templates in R&D's charts are specific to that of AKS or EKS (depending on the version downloaded). Update the Ingress templates to reflect the settings used by the SPT Demo server:

```
kind: Ingress
...
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/redirect-entry-point: https
...
  paths:
    path: /
    pathType: Prefix
```
